name: Q7thoughts
favicon: null
layout_spectrum: 0.2486233483068645
typography_spectrum: 0.5941139825154096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#99b3cc'
    - '#6a88a1'
    - '#5e7a91'
    - '#303d48'
    - '#415667'
  brandStrength: 0.875
  lightness: 0.4484833425376564
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
